[package]
name = "geotab-curve"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = "0.2.17"
chrono = "0.4.31"
arrayvec = "0.7"

[dev-dependencies]
approx = "0.5"
